### ISSUE TITLE
Add Safety Net when creating a dev site

### ISSUE THREAD

**Issue by GeoJunkie** [Automattic/team51-cli#100]
To prevent development sites from running live transactions or emailing production users, Safety Net should be installed and the site should be scrubbed whenever the `create-development-site` is run.

Initially, we will add Safety Net in `mu-plugins`, so the dev can run the commands from WP Admin. Eventually, the CLI should run those commands automatically using either WP CLI commands or via REST API.

As part of installing the plugin, we'll need to check if the autoload script is present (normally in `mu-plugins/mu-autoloader.php`, but it's not part of the scaffold so it may not be the same file every time) and add it if it's not.

**Comment by NickGreen** [comment]
Noting here that the Safety Net plugin currently only runs automatically if `wp_get_environment_type` returns `staging`, `development`, or `local`, so as part of the dev site cloning process, that environment type needs to be set.

**Comment by GeoJunkie** [comment]
I was hoping Pressable would set that automatically if you identify a site as Staging, but it doesn't. [Tested with my own test site](https://my.pressable.com/sites/1247838). I [added a check to the footer](https://github.com/a8cteam51/mikestraw-test/blob/develop/themes/twentytwentytwo-taco/functions.php), [and it returned `production`](https://mikestraw-test-staging.mystagingwebsite.com/).

**Comment by GeoJunkie** [comment]
So far, this is what I have on the list:

- [ ] Take care of [this duplicated code](https://github.com/Automattic/team51-cli/blob/99ff5a003d31b105d6bfd953f0b1066574d64618/src/commands/create-development-site.php#L42-L43) so that everything runs consistently
- [ ] [Update this section to not always use the `develop` branch](https://github.com/Automattic/team51-cli/blob/99ff5a003d31b105d6bfd953f0b1066574d64618/src/commands/create-development-site.php#L165-L183) (if another branch is provided)
- [ ] Add Safety Net to [new site scaffold](https://github.com/Automattic/team51-cli/blob/d3df9989b77cbc0dd9edc6704cce6f49e1bc5e69/src/commands/create-repository.php#L68) as an mu plugin
- [ ] Update `create-development-site`:
  - [ ]  Set development site's environment to `develop`
  - [ ] If code isn't present to load subfolders, add it
  - [ ] Add Safety Net if it's not already installed.

cc: @NickGreen @nate-allen in case there's anything I may be missing.

**Comment by GeoJunkie** [comment]
I'm going to reuse the code in `php-errors` to SFTP to the development sites. The [get_sftp_connection_data](https://github.com/Automattic/team51-cli/blob/6744b84865204094c480115f2385697345a11c39/src/commands/php-errors.php#L224), [add_bot_collaborator_to_site](https://github.com/Automattic/team51-cli/blob/6744b84865204094c480115f2385697345a11c39/src/commands/php-errors.php#L261), and [get_sftp_connection_data_after_adding](https://github.com/Automattic/team51-cli/blob/6744b84865204094c480115f2385697345a11c39/src/commands/php-errors.php#L292) methods can be migrated over to the [API_Helper class](https://github.com/Automattic/team51-cli/blob/a23182cc5a25276ba76d50d95941403e7dd3bc2c/src/helpers/api-helpers.php).

This will let us:
- Add Safety Net to the site as an MU plugin
- Add another MU plugin to set the development site's environment to `develop` ([This is what the plugin code would be](https://github.com/a8cteam51/mikestraw-test-20220801164943/blob/eff18b41125287cc3d77a52f050bb69446b5092f/mu-plugins/set-dev.php). [Demo](https://mikestraw-test-20220801164943-development.mystagingwebsite.com/))
- Check for the existence of an MU Autoloader and add one if it's not already there.

**Comment by NickGreen** [comment]
Noting that this is the working branch https://github.com/Automattic/team51-cli/commits/feature/install-safety-net-on-dev-sites

**Comment by NickGreen** [comment]
PR up here: https://github.com/Automattic/team51-cli/pull/165

Will review and merge Monday.

**Comment by nickpagz** [comment]
@NickGreen does #165 address the original issue? Just wondering if this can be closed.

**Comment by NickGreen** [comment]
Yes! Closing this now.
