### ISSUE TITLE
Scaffolding: Enforce Two-Step Authentication via Jetpack SSO

### ISSUE THREAD

**Issue by tiagonoronha** [Automattic/team51-cli#18]
>If you’d like to improve the security of Secure Sign On, you can choose to force Two-Step Authentication when users log in via WordPress.com. Here is the line of code that you’ll need:
>
>add_filter( 'jetpack_sso_require_two_step', '__return_true' );
>
>Note: This filter only requires that logging in via WordPress.com requires Two-Step Authentication. If you only return true for this filter, then a user could still log in via the default log in form. If you would like to enforce Two-Step Authentication for your site, you could combine the jetpack_sso_require_two_step filter with the jetpack_remove_login_form filter to force users to log in with WordPress.com and use an account with Two-Step Authentication.

From: https://jetpack.com/support/sso/

Let's perhaps create a `mu-plugins` directory in our scaffold templates and in there we can add a file with these filters.

@pippercameron thoughts? 

cc @wrightcj03

**Comment by pippercameron** [comment]
I was thinking about this yesterday on the call and pondered using the Jetpack API to update this setting. That would allow us to turn this on and off in bulk for all of our sites (including sites that are already created) without needing to manage files in GH.

We could use the monitor code we have [here](http://github.com/a8cteam51/team51-monitor/) that already interacts with the API for our a8cteam51 user.

This all assumes we can modify this specific setting, but it appears it should be possible with the API by interacting with either the module or JP settings.

Some reference: https://github.com/Automattic/jetpack/blob/master/docs/rest-api.md

What do you think about this?

**Comment by pippercameron** [comment]
I was thinking about this yesterday on the call and pondered using the Jetpack API to update this setting. That would allow us to turn this on and off in bulk for all of our sites (including sites that are already created) without needing to manage files in GH.

We could use the monitor code we have here that already interacts with the API for our team user.

This all assumes we can modify this specific setting, but it appears it should be possible with the API by interacting with either the module or JP settings.

Some reference: https://github.com/Automattic/jetpack/blob/master/docs/rest-api.md

What do you think about this?

**Comment by tiagonoronha** [comment]
I did not realize that these were regular options, I assumed that the filters were the only way to do it.

The options are: `jetpack_sso_require_two_step` and `jetpack_sso_remove_login_form`.

We can use the monitor code to keep track of sites that do not have these options set to `true`, but where in our stack would you suggest updating these options via the API? 

Using this CLI tool, when creating a new site, the step of connecting Jetpack is being done manually. Also I _think_ the monitor bot only has read access to our team user.

**Comment by pippercameron** [comment]
>Also I think the monitor bot only has read access to our team user.

Ohh. I didn't realize that -- the monitor is the part of the stack where I thought we could enforce/update it from.  So, I guess we have some options to consider:

* Allow the monitor write access so it can manage the updates.
* Do a one-time backfill for all legacy sites to enable them, then use the cli tool to enable two step upon site creation.

**Comment by wrightcj03** [comment]
> Do a one-time backfill for all legacy sites to enable them, then use the cli tool to enable two step upon site creation.

Some legacy sites would need to be excluded and we'd need to coordinate with site admins on others to make sure they had WordPress.com accounts in place before we did this. We'll want to do this eventually so everything is standardized, but newly provisioned sites are the priority for now.

**Comment by pippercameron** [comment]
Roger that. We'll make sure any rollout of this is well coordinated with the rest of the team, as well as site admins.

**Comment by tiagonoronha** [comment]
Since this requires coordination between a team member and site admins, perhaps we can build this as a cli tool command and then add it to the site launch checklist. By that time Jetpack is already connected, so we can updated the option values.

Thoughts?

**Comment by pippercameron** [comment]
> Since this requires coordination between a team member and site admins, perhaps we can build this as a cli tool command and then add it to the site launch checklist. By that time Jetpack is already connected, so we can update the option values. We'd need to store an auth token in the config file.
>
>Thoughts?

Love it. Let's do it. We could make this command like "team51 jetpack" or something so we can add multiple Jetpack interaction options over time. I'm sure we'd find that useful.

**Comment by pippercameron** [comment]
Noting @tiagonoronha will make some progress on the new `team51 jetpack` command this week!

**Comment by tiagonoronha** [comment]
PR here: https://github.com/Automattic/team51-cli/pull/24

As noted, I couldn't find a way to enable the `jetpack_sso_remove_login_form` via the API. I'll probably open an issue in Jetpack to see if they can expose it.

**Comment by pippercameron** [comment]
I left some notes on the PR. Really great work on this @tiagonoronha! This is awesome and also lays the groundwork for some pretty cool stuff in the future.

**Comment by tiagonoronha** [comment]
This has been merged. :)
