### ISSUE TITLE
Alert or prevent script from being executed again if Pressable auth fails 

### ISSUE THREAD

**Issue by tiagonoronha** [Automattic/team51-cli#2]
Sometimes we need to change passwords and this usually invalidates API auth tokens as well. Pressable will lock down an account if too many unsuccessful sign in attempts happen.

The script should warn the user that it failed to log in and/or block further executions of the script so that the account doesn't get accidentally locked.

**Comment by pippercameron** [comment]
Fixed in https://github.com/Automattic/team51-cli/pull/19!
