### ISSUE TITLE
php-errors introduced new dependency?

### ISSUE THREAD

**Issue by mdrovdahl** [Automattic/team51-cli#34]
Ran the below command and got an error...I presume b/c the new(ish) php-errors subcommand depends on a php library that is not installed. If I am correct, perhaps there is a more elegant way to either trap this error.

```
mark.drovdahl@penguin:~/bin/team51-cli$ team51 php-errors site.blog
Checking for updates..
Generated optimized autoload files containing 128 classes


 ______                                ______     _
/\__  _\                              /\  ___\  /' \
\/_/\ \/    __     __      ___ ___    \ \ \__/ /\_, \
   \ \ \  /'__`\ /'__`\  /' __` __`\   \ \___``\/_/\ \
    \ \ \/\  __//\ \L\.\_/\ \/\ \/\ \   \/\ \L\ \ \ \ \
     \ \_\ \____\ \__/.\_\ \_\ \_\ \_\   \ \____/  \ \_\
      \/_/\/____/\/__/\/_/\/_/\/_/\/_/    \/___/    \/_/



Finding site.blog.
Adding temporary bot collaborator to site.blog.
Getting bot collaborator SFTP credentials.
Opening SFTP connection to site.blog.
PHP Fatal error:  Uncaught Error: Class 'phpseclib\Net\SFTP' not found in /home/mark.drovdahl/bin/team51-cli/src/commands/php-errors.php:122
Stack trace:
#0 /home/mark.drovdahl/bin/team51-cli/vendor/symfony/console/Command/Command.php(255): Team51\Command\Get_PHP_Errors->execute()
#1 /home/mark.drovdahl/bin/team51-cli/vendor/symfony/console/Application.php(1001): Symfony\Component\Console\Command\Command->run()
#2 /home/mark.drovdahl/bin/team51-cli/vendor/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand()
#3 /home/mark.drovdahl/bin/team51-cli/vendor/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun()
#4 /home/mark.drovdahl/bin/team51-cli/load-application.php(28): Symfony\Component\Console\Application->run()
#5 /home/mark.drovdahl/bin/team51-cli/team51-cli.php(14): require('/home/mark.drov...')
#6 {main}
  thrown in /home/mark.drovdahl/bin/team51-cli/src/commands/php-errors.php on line 122
```

**Comment by mdrovdahl** [comment]
Ran `$ sudo apt install php-phpseclib` to install the library, but that did not resolve it. Then ran `$ composer update` and found success...not sure which of those solved it, probably the later.

**Comment by pippercameron** [comment]
Yeah, the dependency is in the composer file, but for existing installations composer doesn't update/install new dependencies (only regenerates the autoload files). Thanks for reporting. I'll fix my oversight.

**Comment by pippercameron** [comment]
Hm. I think running `composer update` when dependences are added/updated, which is rare, is better than introducing extra wait time for a command to run by updating every time the team51-cli is started up. It's an extra 5 seconds of wait time per run on my machine/connection  -- even with no updates to process.

I'll ping the team and let them know they need to update, if they haven't already.

Thanks for pointing this out!
