### ISSUE TITLE
Repo creation with master branch rather than trunk

### ISSUE THREAD

**Issue by tiffanybridge** [Automattic/team51-cli#35]
1. Create repo
2. Check for 'trunk' branch. 
3. Find 'master` instead.

**Comment by pippercameron** [comment]
It's like an Easter egg!

**Comment by pippercameron** [comment]
Updated `master` references: https://github.com/Automattic/team51-cli/pull/36

Also updated default branch on new repos to trunk for our internal organization, which is what was causing master to show up on new repos.
