### ISSUE TITLE
When creating temporary development sites, allow for URL to be provided

### ISSUE THREAD

**Issue by mdrovdahl** [Automattic/team51-cli#50]
The `create-development-site` command with the `--temporary-clone` flag creates a site named as such:

`markd@XPS-9310:~/bin/team51-cli$ team51 create-development-site --site-id=1223263 --branch=staging --temporary-clone
.
.
.
Deploy HQ is now set up and ready to start receiving and deploying commits to the new staging site https://daily-dog-development-1631038174.mystagingwebsite.com.`

It would be ideal if user input, eg: something like `--hostname=staging` could be used to instead name the Pressable instance eg: `https://daily-dog-staging.mystagingwebsite.com`

**Comment by ecairol** [comment]
@mdrovdahl I've added a fix in this PR: https://github.com/Automattic/team51-cli/pull/55

Can you give it a try and let me know if works as you would expect? cc @pippercameron

**Comment by ecairol** [comment]
@mdrovdahl yes, I agree with you, `label` is a better option name. 

I've updated the PR and ran a test to make sure it behaves the same way.
