### ISSUE TITLE
take GitHub branch as an argument for: create-development-site --temporary-clone

### ISSUE THREAD

**Issue by mdrovdahl** [Automattic/team51-cli#6]
This would allow for a temporary dev site to be spun up for a given GitHub branch...imagine, a new feature is being developed in `repo-name/sparkle` and then a temporary WP site is quickly provisioned to test that feature with:

`$ team51 create-development-site --site-id=1234567890 --temporary-clone --branch=sparkle`

**Comment by pippercameron** [comment]
```
https://github.com/Automattic/team51-cli/pull/12
