### ISSUE TITLE
Check for `develop` branch and create it if it's not there

### ISSUE THREAD

**Issue by tiffanybridge** [Automattic/team51-cli#7]
Ideally, the script would check for the `develop` branch, and if one doesn't exist (which it usually won't if we're creating a dev site from a recently-launched one), create it before proceeding with the DeployHQ setup.

**Comment by pippercameron** [comment]
Added `develop` branch creation during new repo creation. That should fix most future problems of this.

See: https://github.com/Automattic/team51-cli/commit/7c5a8c3464b39edd5656d11e798fb5b16b126b9a#diff-19820cd447decbb06a9fc3134e576a3cR161

Working on the on-the-fly check when creating a dev site also. Will arrive today.

**Comment by pippercameron** [comment]
Done in https://github.com/Automattic/team51-cli/pull/16!
