### ISSUE TITLE
Allow users of this tool to self-provision access to GitHub repos and Pressable sites

### ISSUE THREAD

**Issue by mdrovdahl** [Automattic/team51-cli#71]
We need to extend this tool to allow users with valid credentials to self-provision access to GitHub repos and Pressable sites.

- [x] Implement the credential system required for the below.
- [ ] Allow existing Members in our GitHub organization to grant themselves "Write" access on repos in our organization
- [x] Allow users to create their own Pressable Collaborator accounts on sites in our Pressable account.

**Comment by mdrovdahl** [comment]
Spoke with @ecairol today and the first step here will be to revisit prior work around issuing individualized tokens (for use with the team51-cli tool).

**Comment by ecairol** [comment]
Related task: https://github.com/a8cteam51/bulk-add-outside-collaborators/issues/1

**Comment by ecairol** [comment]
@mdrovdahl @pippercameron @jonesch would you say any of the following are sensitive data that shouldn't be exposed to contractors outside A8C?

```
DEPLOY_HQ_API_KEY
WPCOM_API_ACCOUNT_TOKEN
FRONT_API_TOKEN
```

These 3 live on `config.json`, and currently, they are all mandatory for the CLI Tool to init properly. The tool validates that these are set before even running the first command.

I'm wondering whether I should change them to be optional values in `config.json`, or if it's ok to share the JSON with them as is?

**Comment by mdrovdahl** [comment]
@ecairol good catch, we should not expose these tokens to non-Automatticians.
