### ISSUE TITLE
Issues with team51 php-errors command

### ISSUE THREAD

**Issue by ecairol** [Automattic/team51-cli#83]
I noticed a few issues when running `team51 php-errors` command.

1. After creating the bot collaborator, lines 75-82, the code attempts to pull FTP user ID by doing this on line 101: `$ftp_user_id = max( array_column( $ftp_data->data, 'id' ) );`, however, that `max()` won't always return the most recent user created. For site `https://dayoneapp-development.mystagingwebsite.com` for instance, it will return Pablo's username

2. The bot collaborator is created without an SFTP user. I found this to be a limitation of Pressable API, but it can be avoided using `bulk_create` and setting up the SFTP role.

3. If the error log is empty, the code never reaches the "delete collaborator" part

4. Because sometimes the user is never deleted, it fails when it tries to create the user again, so it would be good to add a validation when creating the bot collaborator: if it already exists, continue the execution. The current behavior is to exit.

Tested with:
`team51 php-errors https://dayoneapp-development.mystagingwebsite.com --limit=5`

**Comment by ecairol** [comment]
> and could make the command faster if we didn't delete the user on every run.

What a coincidence, I just discussed this with @pippercameron a while ago. We couldn't find any actual reason to delete the user indeed. So I guess we can keep it, just making sure it won't fail when we attempt to create it again (which if I understand correctly, you already confirmed that's the case)

**Comment by nickpagz** [comment]
>So I guess we can keep it, just making sure it won't fail when we attempt to create it again (which if I understand correctly, you already confirmed that's the case)

Nice! But we should validate anyways if the user exists, that way we can bypass user creation altogether if it's not necessary.

**Comment by ecairol** [comment]
Closing this issue as the main bugs have already been fixed by @nickpagz
