### ISSUE TITLE
Repos are created with pre-defined issues

### ISSUE THREAD

**Issue by tiffanybridge** [Automattic/team51-cli#9]
We'd like the repos to be created with predefined issues, for example, launch checklists and the footer credit issue, but ideally possible to expand to project setup checklists or similar.

**Comment by pippercameron** [comment]
Done in https://github.com/Automattic/team51-cli/pull/20!

Issues can now be managed here: https://github.com/a8cteam51/team51-cli-default-issues

Any issue you create there will be automatically added to new repositories created with the `team51 create-repository` command. You can edit, add, and delete issues there as you please and those changes will be reflected each time you create a new repo.

One caveat is label support. Currently, labels you add to the default issues _will_ transfer to the newly created repo, but if they are not in our default list of labels we add, the individual labels will be greyed out. I'm not sure if that's something we need to address right now (let me know!), but it will be fixed anyway when I eventually move label management outside of the CLI tool (currently hardcoded) and into the default issues repository.
