### ISSUE TITLE
Remove wp_access role from pressable-grant-access command

### ISSUE THREAD

**Issue by ecairol** [Automattic/team51-cli#95]
When running `pressable-grant-access` command, contractors are being given a set of permissions, including `wp_access`

This role should be removed. This happens on:

```
$this->api_helper->call_pressable_api(
	'collaborators/batch_create',
	'POST',
	array(
		'email'   => $email,
		'siteIds' => array( $site_id ),
		'roles'   => array( 'clone_site', 'sftp_access', 'download_backups', 'reset_collaborator_password', 'wp_access' ),
	)
);
```

Additionally, add `manage_performance` role

[P2 Conversation](https://to51.wordpress.com/2022/04/28/enabling-cli-access-to-folks-outside-a8c/#comment-24447).

**Comment by ahegyes** [comment]
Closing since this was resolved in #96
